// <auto-generated />
using System;
using BtmManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BtmManager.Migrations
{
    [DbContext(typeof(BtmContext))]
    partial class BtmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("BtmManager.Models.Eintrag", b =>
                {
                    b.Property<int>("EintragId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Abgang")
                        .HasColumnType("REAL");

                    b.Property<float>("AktuellerBestand")
                        .HasColumnType("REAL");

                    b.Property<float>("Anfangsbestand")
                        .HasColumnType("REAL");

                    b.Property<float>("Arbeitsverlust")
                        .HasColumnType("REAL");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Einheit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Farbe")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFirst")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LfdNr")
                        .HasColumnType("TEXT");

                    b.Property<float>("PrakZugang")
                        .HasColumnType("REAL");

                    b.Property<int>("StufId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StufenStufId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TheroZugang")
                        .HasColumnType("REAL");

                    b.Property<bool>("WurdeMarkiert")
                        .HasColumnType("INTEGER");

                    b.HasKey("EintragId");

                    b.HasIndex("StufenStufId");

                    b.ToTable("Einträge");
                });

            modelBuilder.Entity("BtmManager.Models.Projekt", b =>
                {
                    b.Property<int>("ProjektId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BtmBestandsbuchNr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduktNr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Produktbezeichnung")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stufenanzahl")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Zeitraum")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjektId");

                    b.ToTable("Projekte");
                });

            modelBuilder.Entity("BtmManager.Models.Stufe", b =>
                {
                    b.Property<int>("StufId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnzahlEinträge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjektId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StufenNummer")
                        .HasColumnType("INTEGER");

                    b.HasKey("StufId");

                    b.HasIndex("ProjektId");

                    b.ToTable("Stufen");
                });

            modelBuilder.Entity("BtmManager.Models.Eintrag", b =>
                {
                    b.HasOne("BtmManager.Models.Stufe", "Stufen")
                        .WithMany("Einträge")
                        .HasForeignKey("StufenStufId");
                });

            modelBuilder.Entity("BtmManager.Models.Stufe", b =>
                {
                    b.HasOne("BtmManager.Models.Projekt", "Projekte")
                        .WithMany("Stufen")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
