# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BtM_temp.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1806, 457)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_NeuerEintrag = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_NeuerEintrag.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_NeuerEintrag.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pushButton_NeuerEintrag.setDefault(False)
        self.pushButton_NeuerEintrag.setObjectName("pushButton_NeuerEintrag")
        self.gridLayout.addWidget(self.pushButton_NeuerEintrag, 4, 5, 1, 1)
        self.pushButton_speicher = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_speicher.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_speicher.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pushButton_speicher.setAutoDefault(True)
        self.pushButton_speicher.setDefault(False)
        self.pushButton_speicher.setFlat(False)
        self.pushButton_speicher.setObjectName("pushButton_speicher")
        self.gridLayout.addWidget(self.pushButton_speicher, 4, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(1650, 0))
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(175)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(175)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setMinimumSectionSize(50)
        self.gridLayout.addWidget(self.tableWidget, 3, 4, 1, 3)
        self.radioButton_gramm = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_gramm.setObjectName("radioButton_gramm")
        self.gridLayout.addWidget(self.radioButton_gramm, 2, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 7, 1, 1)
        self.label_pfad = QtWidgets.QLabel(self.centralwidget)
        self.label_pfad.setText("")
        self.label_pfad.setObjectName("label_pfad")
        self.gridLayout.addWidget(self.label_pfad, 2, 6, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 7, 1, 1)
        self.pushButton_EintragLoeschen = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_EintragLoeschen.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_EintragLoeschen.setMaximumSize(QtCore.QSize(300, 300))
        self.pushButton_EintragLoeschen.setAutoDefault(False)
        self.pushButton_EintragLoeschen.setDefault(False)
        self.pushButton_EintragLoeschen.setObjectName("pushButton_EintragLoeschen")
        self.gridLayout.addWidget(self.pushButton_EintragLoeschen, 4, 4, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Name")
        self.gridLayout.addWidget(self.treeWidget, 3, 1, 1, 1)
        self.radioButton_kilogramm = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_kilogramm.setObjectName("radioButton_kilogramm")
        self.gridLayout.addWidget(self.radioButton_kilogramm, 1, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 1)
        self.ProjektnameLabel = QtWidgets.QLabel(self.centralwidget)
        self.ProjektnameLabel.setObjectName("ProjektnameLabel")
        self.gridLayout.addWidget(self.ProjektnameLabel, 1, 5, 1, 1)
        self.LogbuchLabel = QtWidgets.QLabel(self.centralwidget)
        self.LogbuchLabel.setObjectName("LogbuchLabel")
        self.gridLayout.addWidget(self.LogbuchLabel, 2, 5, 1, 1)
        self.label_projekt = QtWidgets.QLabel(self.centralwidget)
        self.label_projekt.setText("")
        self.label_projekt.setObjectName("label_projekt")
        self.gridLayout.addWidget(self.label_projekt, 1, 6, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 7, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1806, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuWerkzeuge = QtWidgets.QMenu(self.menubar)
        self.menuWerkzeuge.setObjectName("menuWerkzeuge")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNeues_Projekt = QtWidgets.QAction(MainWindow)
        self.actionNeues_Projekt.setWhatsThis("")
        self.actionNeues_Projekt.setObjectName("actionNeues_Projekt")
        self.actionProjekt_ffnen = QtWidgets.QAction(MainWindow)
        self.actionProjekt_ffnen.setObjectName("actionProjekt_ffnen")
        self.actionNeues_Logbuch = QtWidgets.QAction(MainWindow)
        self.actionNeues_Logbuch.setObjectName("actionNeues_Logbuch")
        self.actionLogbuch_laden = QtWidgets.QAction(MainWindow)
        self.actionLogbuch_laden.setObjectName("actionLogbuch_laden")
        self.actionLogbuch_speichen = QtWidgets.QAction(MainWindow)
        self.actionLogbuch_speichen.setObjectName("actionLogbuch_speichen")
        self.actionNeues_Projekt_2 = QtWidgets.QAction(MainWindow)
        self.actionNeues_Projekt_2.setObjectName("actionNeues_Projekt_2")
        self.actionLogbuch_speichern_unter = QtWidgets.QAction(MainWindow)
        self.actionLogbuch_speichern_unter.setObjectName("actionLogbuch_speichern_unter")
        self.actionBerechnen = QtWidgets.QAction(MainWindow)
        self.actionBerechnen.setObjectName("actionBerechnen")
        self.menuDatei.addAction(self.actionNeues_Projekt)
        self.menuDatei.addAction(self.actionProjekt_ffnen)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionNeues_Logbuch)
        self.menuDatei.addAction(self.actionLogbuch_laden)
        self.menuDatei.addAction(self.actionLogbuch_speichen)
        self.menuDatei.addAction(self.actionLogbuch_speichern_unter)
        self.menuWerkzeuge.addAction(self.actionBerechnen)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuWerkzeuge.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BtM Buchhalter"))
        self.pushButton_NeuerEintrag.setText(_translate("MainWindow", "Neuer Eintrag"))
        self.pushButton_speicher.setText(_translate("MainWindow", "Speichern"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lfd. Nr."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Datum"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Anfangsbestand"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Theor. Zugang"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Prakt. Zugang"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Arbeitsverlust"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Abgang"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Aktueller \n"
" Bestand"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Bemerkung"))
        self.radioButton_gramm.setText(_translate("MainWindow", "Gramm"))
        self.pushButton_EintragLoeschen.setText(_translate("MainWindow", "Letzten Eintrag löschen"))
        self.radioButton_kilogramm.setText(_translate("MainWindow", "Kilogramm"))
        self.ProjektnameLabel.setText(_translate("MainWindow", "Projektname:"))
        self.LogbuchLabel.setText(_translate("MainWindow", "Logbuch:"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.menuWerkzeuge.setTitle(_translate("MainWindow", "Werkzeuge"))
        self.actionNeues_Projekt.setText(_translate("MainWindow", "Neues Projekt"))
        self.actionNeues_Projekt.setStatusTip(_translate("MainWindow", "Erstellt ein neues Projekt(Ordner)"))
        self.actionNeues_Projekt.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
        self.actionProjekt_ffnen.setText(_translate("MainWindow", "Projekt öffnen"))
        self.actionProjekt_ffnen.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
        self.actionNeues_Logbuch.setText(_translate("MainWindow", "Neues Logbuch"))
        self.actionNeues_Logbuch.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionLogbuch_laden.setText(_translate("MainWindow", "Logbuch öffnen"))
        self.actionLogbuch_laden.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionLogbuch_speichen.setText(_translate("MainWindow", "Logbuch speichen"))
        self.actionLogbuch_speichen.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionNeues_Projekt_2.setText(_translate("MainWindow", "Neues Projekt"))
        self.actionLogbuch_speichern_unter.setText(_translate("MainWindow", "Logbuch speichern unter"))
        self.actionBerechnen.setText(_translate("MainWindow", "Berechnen"))
        self.actionBerechnen.setShortcut(_translate("MainWindow", "F5"))
